"""Offline test for WedgeRunner patch application and test_command execution.

This drives WedgeRunner against an offline patch (no live LLM call) and
verifies the patch is written to a worktree, test_command is executed, and
test_passed reflects the real exit code. Also covers default models,
base_url override, and provider dispatch.
"""
import asyncio
import os
import subprocess

import pytest
import yaml

import wedge.cli as wedge_cli
from wedge.runner import WedgeRunner, _extract_patch_from_output, apply_patch


FAKE_PATCH = (
    "--- a/main.py\n"
    "+++ b/main.py\n"
    "@@ -3 +3 @@\n"
    "-# Generated by t1\n"
    "+# patched hello world\n"
)


def test_extract_clean_diff():
    out = _extract_patch_from_output(
        "loose text\n--- a/x.py\n+++ b/x.py\n@@\n-old\n+new\n"
    )
    assert out.lstrip().startswith("--- a/x.py")


def test_extract_search_replace_block():
    out = _extract_patch_from_output("### search: foo\n### replace: foo2")
    assert "foo" in out and "foo2" in out


def test_extract_returns_empty_for_plain_text():
    assert _extract_patch_from_output("no diff here") == ""


def test_apply_patch_modifies_real_file(tmp_path):
    f = tmp_path / "hello.txt"
    f.write_text("line1\nold\nline3\n")
    patch = (
        "--- a/hello.txt\n"
        "+++ b/hello.txt\n"
        "@@ -1,3 +1,3 @@\n"
        " line1\n"
        "-old\n"
        "+new\n"
        " line3\n"
    )
    assert apply_patch(patch, str(f))
    assert "new" in f.read_text()
    assert "old" not in f.read_text()


def test_runner_writes_patch_and_executes_test_command(monkeypatch):
    """End-to-end: patch is written to worktree, test_command runs, exit
    code is honored."""
    # Force a clean, non-repo worktree path (deterministic)
    tmp = monkeypatch.setattr("wedge.runner.os.path.exists", lambda p: False)
    # Use temp repo path so runner falls back to mkdtemp
    runner = WedgeRunner(
        "t1",
        repo_path="/tmp/nonexistent_for_runner",
        provider="openai",
        base_url="https://my-proxy.example.com/v1",
    )
    assert runner.base_url == "https://my-proxy.example.com/v1"

    # `false` exits 1
    async def go():
        return await runner.run("ignored", "false", patch=FAKE_PATCH)

    r = asyncio.run(go())
    assert r["runner_id"] == "t1"
    assert r["patch"]["main.py"] == FAKE_PATCH
    # exit code 1 -> test_passed False
    assert r["test_passed"] is False

    # `true` exits 0
    async def go2():
        return await runner.run("ignored", "true", patch=FAKE_PATCH)

    r2 = asyncio.run(go2())
    assert r2["test_passed"] is True


def test_runner_uses_current_models_by_default():
    r_openai = WedgeRunner("a", "/tmp/x", provider="openai")
    r_anth = WedgeRunner("b", "/tmp/x", provider="anthropic")
    assert r_openai._DEFAULT_MODEL == "gpt-4.1-mini"
    assert r_anth._DEFAULT_MODEL == "claude-sonnet-4-20250514"


def test_runner_accepts_base_url_override():
    r = WedgeRunner(
        "c", "/tmp/x", provider="openai", base_url="https://custom.example.com/v1"
    )
    assert r.base_url == "https://custom.example.com/v1"


def test_runner_rejects_unknown_provider():
    with pytest.raises(ValueError):
        WedgeRunner("x", "/tmp/x", provider="google")


def test_runner_applies_mocked_llm_output_to_worktree(tmp_path, monkeypatch):
    """End-to-end via the LLM path: mocked model output is written to the
    worktree, test_command runs, and test_passed reflects the exit code."""
    import pathlib

    # A real (non-git) repo dir whose main.py matches the patch target line.
    (tmp_path / "main.py").write_text("# line1\n# line2\n# Generated by t1\n")

    runner = WedgeRunner(
        "llm1",
        repo_path=str(tmp_path),
        provider="openai",
        base_url="https://my-proxy.example.com/v1",
    )
    # Recorded/mock LLM response.
    async def mock_llm(prompt):
        return FAKE_PATCH

    monkeypatch.setattr(runner, "_generate_patch_from_llm", mock_llm)
    # Keep the worktree so we can inspect it after the run.
    monkeypatch.setattr(runner, "_teardown_worktree", lambda: None)

    async def go():
        return await runner.run("refactor main.py", "true")

    r = asyncio.run(go())

    assert r["patch_applied"] is True
    wt = pathlib.Path(runner.worktree_path)
    assert "# patched hello world" in (wt / "main.py").read_text()
    # `true` exits 0
    assert r["test_passed"] is True


def test_cli_passes_base_url_from_task_yaml(monkeypatch, tmp_path):
    """`wedge run` reads base_url from task.yaml (and WEDGE_BASE_URL) and
    forwards it to each WedgeRunner."""
    captured = {}

    class FakeRunner:
        def __init__(self, runner_id, repo_path, provider="anthropic", base_url=None, model=None):
            captured[runner_id] = base_url

        async def run(self, prompt, test_cmd, patch=None):
            return {
                "runner_id": "x",
                "patch": {},
                "patch_applied": True,
                "test_passed": True,
                "budget_remaining": None,
            }

    monkeypatch.setattr(wedge_cli, "WedgeRunner", FakeRunner)
    monkeypatch.setattr(wedge_cli, "compare_patches", lambda patches: {})
    monkeypatch.setattr(wedge_cli, "generate_report", lambda *a, **k: "")

    task_file = tmp_path / "task.yaml"
    task_file.write_text(
        yaml.safe_dump(
            {
                "name": "t",
                "prompt": "p",
                "test_command": "true",
                "runners": 2,
                "provider": "openai",
                "base_url": "https://custom.example.com/v1",
            }
        )
    )

    async def go():
        await wedge_cli.run_task(str(task_file))

    asyncio.run(go())
    assert captured == {"R0": "https://custom.example.com/v1",
                         "R1": "https://custom.example.com/v1"}


def test_cli_falls_back_to_wedge_base_url_env(monkeypatch, tmp_path):
    captured = {}

    class FakeRunner:
        def __init__(self, runner_id, repo_path, provider="anthropic", base_url=None, model=None):
            captured[runner_id] = base_url

        async def run(self, prompt, test_cmd, patch=None):
            return {
                "runner_id": "x",
                "patch": {},
                "patch_applied": True,
                "test_passed": True,
                "budget_remaining": None,
            }

    monkeypatch.setattr(wedge_cli, "WedgeRunner", FakeRunner)
    monkeypatch.setattr(wedge_cli, "compare_patches", lambda patches: {})
    monkeypatch.setattr(wedge_cli, "generate_report", lambda *a, **k: "")
    monkeypatch.setenv("WEDGE_BASE_URL", "https://env.example.com/v1")

    task_file = tmp_path / "task.yaml"
    task_file.write_text(
        yaml.safe_dump(
            {"name": "t", "prompt": "p", "test_command": "true", "runners": 1}
        )
    )

    async def go():
        await wedge_cli.run_task(str(task_file))

    asyncio.run(go())
    assert captured["R0"] == "https://env.example.com/v1"
